app/alumnos/forms/AlumnoForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.widgets import HiddenInput
from wtforms.validators import DataRequired, Email, Length
from flask_wtf.file import FileField, FileRequired, FileAllowed


class VerAlumnoForm(FlaskForm):
    id = IntegerField(widget=HiddenInput())
    nombre = StringField('Nombre')
    apellido = StringField('Apellido')
    dni = StringField('DNI')
    correo = StringField('Correo')
    celular = StringField('Celular')
    slug = StringField('Slug')
    submit = SubmitField('Guardar')

app/alumnos/forms/register.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length
from flask_wtf.file import FileField, FileRequired, FileAllowed


class UploadFromExcel(FlaskForm):
    document = FileField('document', 
                         validators=[FileRequired('Debe subir un documento'),
                                     FileAllowed(['csv'], 
                                                 'El documento debe ser formato CSV')])
    submit = SubmitField('Registrar ahora')

class UploadFromPDF(FlaskForm):
    document = FileField('document', 
                         validators=[FileRequired('Debe subir un documento'),
                                     FileAllowed(['pdf'],
                                                 'El documento debe ser formato PDF')])
    submit = SubmitField('Subir ahora')

app/alumnos/__init__.py
from flask import Blueprint
alumnos_bp = Blueprint('alumnos', __name__, template_folder='templates')
from . import routes

app/alumnos/business/__init__.py
from app.models import CursoProgramado
from app import db
from datetime import datetime


def guardar_curso_programado(curso, fecha_ini):
    try:
        cp = CursoProgramado()
        cp.curso_id = curso.id
        cp.fecha_inicio = datetime.strptime(fecha_ini, '%d/%m/%Y') 
        db.session.add(cp)
        db.session.commit()
        return "El Curso fue programado exitósamente"
    except Exception as e:
        print(e)
        return None

def actualizar_curso_programado(pid, fecha_ini):
    try:
        cp = CursoProgramado.query.filter_by(id=pid).first()
        cp.fecha_inicio = datetime.strptime(fecha_ini, '%d/%m/%Y') 
        db.session.add(cp)
        db.session.commit()
        return "El Curso fue actualizado exitósamente"
    except Exception as e:
        print(e)
        return None
 

app/alumnos/routes.py
from flask import render_template, redirect, url_for, request, flash
from flask_login import LoginManager, logout_user, current_user, login_user, login_required
from app.alumnos import alumnos_bp
from app.models import Alumno
from datetime import datetime
from app.alumnos.forms.register import UploadFromExcel
from app import db
from app.alumnos.forms.AlumnoForm import VerAlumnoForm
from flask import jsonify
import csv
from sqlalchemy import exc


@alumnos_bp.route('/alumnos/lista-completa')
@login_required
def lista_completa():
    if request.method == 'GET':
        op = request.args.get("op")
        if op == 'filtro-mixto':
            slug = request.args.get("slug").lower() 
            slug = "%{}%".format(slug)
            from sqlalchemy import or_
            lista = Alumno.query.filter(or_(Alumno.nombre.like(slug),
                                            Alumno.apellido.like(slug),
                                            Alumno.dni.like(slug),
                                            Alumno.correo.like(slug),
                                            Alumno.celular.like(slug),
                                            Alumno.slug.like(slug)
                                            )
                                        ).all()
            return jsonify([z.to_json() for z in lista])
        else:
            lista = Alumno.query.all()
            return render_template("alumnos/lista-completa.html", lista=lista)

@alumnos_bp.route('/alumnos/registrar-desde-excel', methods=['GET', 'POST'])
@login_required
def registrar_desde_excel():
    form = UploadFromExcel()
    if request.method == 'GET':
        return render_template("alumnos/registrar-desde-excel.html", form=form)
    elif request.method == 'POST':
        if form.validate_on_submit():
            file = form.document.data
            data = file.stream.read().decode("ISO-8859-1")
            spamreader = csv.reader(data.splitlines())
            for row in spamreader:
                if len(row) > 0:
                    b = Alumno.query.filter(Alumno.dni == row[0]).first()
                    if not b:
                        if row[0] and row[1] and row[2] and row[3] and row[4] and row[5]:
                            a = Alumno()
                            a.dni = row[0].lower()
                            a.nombre = row[1].lower()
                            a.apellido = row[2].lower()
                            a.correo = row[3].lower()
                            a.celular = row[4].lower()
                            a.slug = row[5].lower()
                            db.session.add(a)
                            db.session.commit()
                        else:
                            flash("Algunos registros del CSV poseen campos no llenados") 
                    else:
                        flash("Se encontró en el CSV un dni que ya está registrado en la base de datos.") 
                else:
                    flash("El documento está vacio")

            flash("Los alumnos se registraron exitosamente")
            return render_template("alumnos/registrar-desde-excel.html", form=form)
        else:
            return render_template("alumnos/registrar-desde-excel.html", form=form)

@alumnos_bp.route('/alumnos/ver-alumno/<int:id>', methods=['GET', 'POST', 'DELETE'])
@login_required
def ver_alumno(id):
    form = VerAlumnoForm()
    if request.method == 'GET':
        p = Alumno.query.filter_by(id=id).first() 
        form.id.data = p.id
        form.nombre.data = p.nombre
        form.apellido.data = p.apellido
        form.dni.data = p.dni
        form.correo.data = p.correo
        form.celular.data = p.celular
        form.slug.data = p.slug
        return render_template("alumnos/ver-alumno.html", form=form)
    elif request.method == 'POST':
        try:
            a = Alumno.query.filter_by(id=id).first()
            a.nombre = form.nombre.data.lower()
            a.apellido = form.apellido.data.lower()
            a.dni = form.dni.data
            a.correo = form.correo.data
            a.celular = form.celular.data
            a.slug = form.slug.data
            db.session.add(a)
            db.session.commit()
            flash("Datos actualizados exitosamente")
            return render_template("alumnos/ver-alumno.html", form=form)
        except Exception as e:
            error = 'Problema al guardar, verifique los datos ingresados'
            return render_template("alumnos/ver-alumno.html", form=form)
    elif request.method == 'DELETE':
        try:
            c = Alumno.query.get(id)
            db.session.delete(c)
            db.session.commit()
            lista = Alumno.query.all()
            return render_template("alumnos/lista-completa.html", lista=lista)
        except exc.IntegrityError:
            db.session.rollback()
            return "error"

app/templates/alumnos/lista-completa.html
{% extends "base_template.html" %}

{% block content %} 
<script>
  $( function() {
    $( ".my-atepicker" ).datepicker(
      $.datepicker.regional[ "es" ]
    );
    $( ".my-atepicker" ).datepicker( "option", "dateFormat", "dd/mm/yy");
  });
</script>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/alumnos/partials/menu-alumnos-tpl.html' %}
    </div>
    <div class="column is-9"> 
      <p class="subtitle"><strong>Lista completa de Alumnos</strong></p>
      <table class="class table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <tr>
          <th>#</th><th>DNI</th><th>Nombres</th>
          <th>Apellidos</th><th>Correo</th><th>Celular</th><th>Slug</th>
          <th>Acciones</th>
        </tr>
        {% for e in lista %}
          <tr>
            <td>{{ loop.index }}</td>
            <td>{{ e.dni }}</td>
            <td>{{ e.nombre | title }}</td>
            <td>{{ e.apellido | title}}</td>
            <td>{{ e.correo }}</td>
            <td>{{ e.celular }}</td>
            <td>{{ e.slug }}</td>
            <td class="has-text-centered">
              <a href="{{ url_for('alumnos.ver_alumno', id=e.id) }}">
                <span class="icon"><i class="fas fa-edit" title="Editar"></i> </span>
              </a>
              <span class="icon" style="cursor: pointer" onclick="eliminarAlumno({{ e.id }})"><i class="fas fa-trash" title="Eliminar"></i> </span>
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>
<script>
  function eliminarAlumno(idx){
    var r = confirm("¿Estás seguro que deseas eliminar este registro?");
    if(r == true){
        $.ajax({
          url: '/alumnos/ver-alumno/'+idx,
          type: 'DELETE',
          data: JSON.stringify({ id: idx} ),
          success: function(result) {
            console.log(result);
            if (result == "error"){
              alert("No se pudo borrar, el registro está vinculado a un curso programado")
            }
            window.location.reload();
          }
      });
    } 
  }
</script>
{% endblock %}


 

app/templates/alumnos/registrar-desde-excel.html
{% extends "base_template.html" %}

{% block content %}
<script>
  $(function () {
    $(".my-atepicker").datepicker(
      $.datepicker.regional["es"]
    );
    $(".my-atepicker").datepicker("option", "dateFormat", "dd/mm/yy");
  });
</script>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/alumnos/partials/menu-alumnos-tpl.html' %}
    </div>
    <div class="column is-9">
      <p class="subtitle"><strong>Registrar desde Excel</strong></p>
      <form action="{{ url_for('alumnos.registrar_desde_excel') }}" method="post" class="form"
        enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <div class="field">
          <label class="label">Subir archivo</label>
          <div class="control">
            <input type="file" name="document" class="input">
          </div>
          {% for error in form.document.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
        </div>
        <nav class="level">
          <!-- Right side -->
          <div class="level-right">
            <p class="level-item">
              {{ form.submit(class_="button is-link") }}
            </p>
          </div>
        </nav>
      </form>
      <br><br>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul class=flashes>
        {% for message in messages %}
        <li><span class="has-text-link">{{ message }}</span></li>
        {% endfor %}
      </ul>
      {% endif %}
      {% endwith %}
      <br>
      <section>
        <strong>Formato de CSV</strong>
        <p>
          [DNI] [Nombres] [Apellidos] [Correo] [Celular] [Etiqueta] 
        </p>
      </section>
    </div> 
  </div>
</div>

{% endblock %}

app/templates/alumnos/ver-alumno.html
{% extends "base_template.html" %}

{% block content %}
<div id="vm" class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/alumnos/partials/menu-alumnos-tpl.html' %}
    </div>
    <div class="column is-9">
        <p class="subtitle"><strong>Ver alumno</strong></p>
        <form action="{{ url_for('alumnos.ver_alumno', id=form.id.data) }}" 
            method="post" class="form" novalidate>
          {{ form.hidden_tag() }}
          <div class="field">
            <label class="label"> {{ form.nombre.label }}</label>
            <div class="control">
              {{ form.nombre(class_="input capitalize") }}
            </div>
            {% for error in form.nombre.errors %}
            <span class="has-text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          <div class="field">
            <label class="label"> {{ form.apellido.label }}</label>
            <div class="control">
              {{ form.apellido(class_="input capitalize") }}
            </div>
            {% for error in form.apellido.errors %}
            <span class="has-text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          <div class="field">
            <label class="label"> {{ form.dni.label }}</label>
            <div class="control">
              {{ form.dni(class_="input") }}
            </div>
            {% for error in form.dni.errors %}
            <span class="has-text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          <div class="field">
            <label class="label"> {{ form.correo.label }}</label>
            <div class="control">
              {{ form.correo(class_="input") }}
            </div>
            {% for error in form.correo.errors %}
            <span class="has-text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          <div class="field">
            <label class="label"> {{ form.celular.label }}</label>
            <div class="control">
              {{ form.celular(class_="input") }}
            </div>
            {% for error in form.celular.errors %}
            <span class="has-text-danger">{{ error }}</span>
            {% endfor %}
          </div>
          <div class="field">
            <label class="label"> {{ form.slug.label }}</label>
            <div class="control">
              {{ form.slug(class_="input") }}
            </div>
            {% for error in form.slug.errors %}
            <span class="has-text-danger">{{ error }}</span>
            {% endfor %}
          </div>


          <div>
            <span class="has-text-danger">{{ error }}</span>
          </div>
          <div class="field">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                <ul class=flashes>
                {% for message in messages %}
                  <li><span class="has-text-link">{{ message }}</span></li>
                {% endfor %}
                </ul>
              {% endif %}
            {% endwith %}
          </div>
          <nav class="level">
            <!-- Right side -->
            <div class="level-right">
              <p class="level-item">
                {{ form.submit(class_="button is-link") }}
              </p>
            </div>
          </nav>
        </form>
      </div>

     
  </div>
</div>
<script>
  const vm = new Vue({ // Again, vm is our Vue instance's name for consistency.
    el: '#vm',
    delimiters: ['[[', ']]'],
    data: {
        isActive: false,
        lista: [],
        slug: ""
    },
    methods: {
        buscarAlumnoXFiltro: function() {
          var params = { op: 'filtro-mixto', slug: this.slug};
          try {
            axios.get('{{url_for("alumnos.lista_completa")}}', {params: params})
            .then(
              response => {
                this.lista = [];
                var data = response.data;
                for(i=0;i<data.length; i++){
                  var item = data[i];
                  item.checked = false;
                  this.lista.push(item);
                }
              }
            )
            .catch(error => {
              console.log(error)
            })
            //.finally(() => this.loading = false)
          } catch (error) {
            console.log(error);
          }
        }, 
        subirCertificado: function(id){
          var c = confirm("¿Está seguro que desea eliminar este registro?");
          if(c){
            var params = { id: id};
            axios.delete('{{url_for("cursos.alumnos_registrados")}}', {params: params})
            .then(
              response => {
                if(response.data.message == "ok"){
                  window.location.reload()
                }
              }
            )
            .catch(error => {
              console.log(error)
            })
          }else{
            console.log("no");
          }
        },
        retirarAlumno: function(id){
          var c = confirm("¿Está seguro que desea eliminar este registro?");
          if(c){
            var params = { id: id};
            axios.delete('{{url_for("cursos.alumnos_registrados")}}', {params: params})
            .then(
              response => {
                if(response.data.message == "ok"){
                  window.location.reload()
                }
              }
            )
            .catch(error => {
              console.log(error)
            })
          }else{
            console.log("no");
          }
        },
        guardarAlumnosSeleccionados: function(){
          let ids = []
          for(i=0;i<this.lista.length; i++){
            var item = this.lista[i];
            if(item.checked){
              ids.push(item.id);
            }
          }
          // Inscribir alumnos en el curso.
          var cid = '{{form.id.data}}';
          var params = { op: 'inscribir-alumnos',cid: cid ,ids: ids};
          axios.put('{{url_for("cursos.cursos_programados")}}', {params: params})
            .then(
              response => {
                if(response.data.message == "ok"){
                  this.isActive = false;
                  window.location.reload()
                }
              }
            )
            .catch(error => {
              console.log(error)
            })
        },
        launch: function() {
          this.isActive = true;
        },
        close: function() {
          this.isActive = false;
        }
    }
})
</script>
{% endblock %}