app/cursos/forms/CursosForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, IntegerField
from wtforms.widgets import HiddenInput
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length
from datetime import datetime
from app.models import Curso

def get_cursos():
    return Curso.query.all()

class ProgramarCursoForm(FlaskForm):
    curso = QuerySelectField(query_factory=get_cursos, get_label='nombre')
    fecha_ini = StringField('F.Inicio', validators=[DataRequired(message="Ingresa una fecha válida")])
    fecha_fin = StringField('F.Fin', validators=[DataRequired(message="Ingresa una fecha válida")])
    submit = SubmitField('Guardar')


class VerCursoForm(FlaskForm):
    id = IntegerField(widget=HiddenInput())
    curso = StringField('Curso', render_kw={'readonly': True})
    fecha_ini = StringField('F.Inicio', validators=[DataRequired(message="Ingresa una fecha válida")])
    submit = SubmitField('Guardar')

app/cursos/forms/LoginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email, Length

class LoginForm(FlaskForm):
    username = StringField('Usuario', validators=[DataRequired(message="Ingresa un nombre de usuario válido"), Length(max=64)])
    password = PasswordField('Contraseña', validators=[DataRequired(message="Ingresa una contraseña")]) 
    remember_me = BooleanField('Recuérdame')
    submit = SubmitField('Ingresar')

app/dashboard/forms/CursosForm.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, IntegerField
from wtforms.widgets import HiddenInput
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length
from datetime import datetime
from app.models import Curso

def get_cursos():
    return Curso.query.all()

class ProgramarCursoForm(FlaskForm):
    curso = QuerySelectField(query_factory=get_cursos, get_label='nombre')
    fecha_ini = StringField('Fecha Inicio', validators=[DataRequired(message="Ingresa una fecha válida")])
    submit = SubmitField('Guardar')


class VerCursoForm(FlaskForm):
    id = IntegerField(widget=HiddenInput())
    curso = StringField('Curso', render_kw={'readonly': True})
    fecha_ini = StringField('Fecha Inicio', validators=[DataRequired(message="Ingresa una fecha válida")])
    submit = SubmitField('Guardar')

app/cursos/__init__.py
from flask import Blueprint
cursos_bp = Blueprint('cursos', __name__, template_folder='templates')
from . import routes

app/cursos/business/__init__.py
from app.models import CursoProgramado
from app import db
from datetime import datetime


def guardar_curso_programado(curso, fecha_ini, fecha_fin):
    try:
        cp = CursoProgramado()
        cp.curso_id = curso.id
        cp.fecha_inicio = datetime.strptime(fecha_ini, '%d/%m/%Y') 
        cp.fecha_fin = datetime.strptime(fecha_fin, '%d/%m/%Y') 
        db.session.add(cp)
        db.session.commit()
        return "El Curso fue programado exitósamente"
    except Exception as e:
        print(e)
        return None

def actualizar_curso_programado(pid, fecha_ini):
    try:
        cp = CursoProgramado.query.filter_by(id=pid).first()
        cp.fecha_inicio = datetime.strptime(fecha_ini, '%d/%m/%Y') 
        db.session.add(cp)
        db.session.commit()
        return "El Curso fue actualizado exitósamente"
    except Exception as e:
        print(e)
        return None

app/cursos/routes.py
from flask import render_template, redirect, url_for, request, flash, abort
from flask_login import LoginManager, logout_user, current_user, login_user, login_required
from werkzeug.urls import url_parse
from app import login_manager
from app.cursos import cursos_bp
from .forms.LoginForm import LoginForm
from .forms.CursosForm import ProgramarCursoForm, VerCursoForm
from app.models import Usuario, Curso, CursoProgramado, AlumnoCurso
from app.snippets import is_safe_url
from datetime import datetime
from flask import jsonify
from app.cursos.business import guardar_curso_programado, actualizar_curso_programado
from app import db
from app.alumnos.forms.register import UploadFromPDF
from werkzeug.utils import secure_filename
import os
import uuid
from flask import current_app
from flask import send_from_directory


@cursos_bp.route('/cursos/cursos-disponibles') 
@login_required
def cursos_disponibles():
    if request.method == 'GET':
        lista_cursos = Curso.query.all()
        return render_template("cursos/cursos-disponibles.html", lista_cursos=lista_cursos)

@cursos_bp.route('/cursos/cursos-programados', methods=['GET', 'DELETE', 'PUT'])
@login_required
def cursos_programados():
    if request.method == 'GET':
        lista_cursos = CursoProgramado.query.order_by(CursoProgramado.fecha_inicio.asc()).all()
        return render_template("cursos/cursos-programados.html", lista_cursos=lista_cursos)
    elif request.method == 'DELETE':
        content = request.get_json(force = True)
        c = CursoProgramado.query.get(int(content['id']))
        db.session.delete(c)
        db.session.commit()
        lista_cursos = CursoProgramado.query.order_by(CursoProgramado.fecha_inicio.asc()).all()
        return render_template("cursos/cursos-programados.html", lista_cursos=lista_cursos)
    elif request.method == 'PUT':
        data = request.get_json(force = True)["params"]
        if data["op"] == 'inscribir-alumnos':
            print(data)
            ids = data["ids"]
            for id in ids:
                ex = AlumnoCurso.query.filter(AlumnoCurso.alumno_id==id,
                                              AlumnoCurso.curso_prog_id==data["cid"]).first()

                if not ex:
                    c = AlumnoCurso()
                    c.alumno_id = id
                    c.curso_prog_id = data["cid"]
                    db.session.add(c)
                    db.session.commit()
            return jsonify({"message": "ok"})

@cursos_bp.route('/cursos/cursos-programados/descargar-certificado/<string:filename>', methods=['GET', 'POST'])
@login_required
def download_file(filename): 
    try:
        return send_from_directory(current_app.config["REPO_CERTIFICADOS"], 
                                   filename=filename, as_attachment=True)
    except FileNotFoundError:
        abort(404)

@cursos_bp.route('/cursos/cursos-programados/<int:cid>/alumno/<int:aid>/subir-certificado', methods=['GET', 'POST'])
@login_required
def curso_alumno_subir_certificado(cid, aid):
    form = UploadFromPDF()
    if request.method == 'GET':
        return render_template("cursos/subir-certificado.html", form=form, cid=cid, aid=aid)
    elif request.method == 'POST':
        if form.validate_on_submit():
            id_pdf = uuid.uuid1().time
            file = form.document.data
            filename = str(id_pdf)+str(".pdf")
            filedir = os.path.join(current_app.config["REPO_CERTIFICADOS"], filename)
            print(filedir)
            file.save(filedir)
            cp = AlumnoCurso.query.filter_by(alumno_id=aid, curso_prog_id=cid).first()
            cp.certificado = filename
            db.session.merge(cp)
            db.session.commit()
            flash("Certificado registrado exitosamente")
            return render_template("cursos/subir-certificado.html", form=form, cid=cid, aid=aid)
        else:
            return render_template("cursos/subir-certificado.html", form=form, cid=cid, aid=aid)

@cursos_bp.route('/cursos/cursos-programados/<int:id>', methods=['GET', 'POST'])
@login_required
def ver_curso_programado(id):
    form = VerCursoForm()
    if request.method == 'GET':
        p = CursoProgramado.query.filter_by(id=id).first()
        lista = AlumnoCurso.query.filter_by(curso_prog_id=p.id).all()
        form.id.data = p.id
        form.curso.data = p.curso.nombre
        form.fecha_ini.data = datetime.strftime(p.fecha_inicio, '%d/%m/%Y')
        return render_template("cursos/ver-curso-programado.html", form=form, lista=lista)
    elif request.method == 'POST':
        message = actualizar_curso_programado(form.id.data, form.fecha_ini.data)
        lista = AlumnoCurso.query.filter_by(curso_prog_id=form.id.data).all()
        if message:
            flash(message)
            return render_template("cursos/ver-curso-programado.html", form=form, lista=lista)
        else:
            error = 'Problema al guardar, verifique los datos ingresados'
            return render_template("cursos/ver-curso-programado.html", form=form, lista=lista, error=error)

        return render_template("cursos/ver-curso-programado.html", form=form, lista=lista)

@cursos_bp.route('/cursos/programar-curso', methods=['GET', 'POST'])
@login_required
def programar_curso():
    form = ProgramarCursoForm()
    error = None
    if request.method == 'POST':
        if form.validate_on_submit():
            curso = form.curso.data
            fecha_ini = form.fecha_ini.data
            fecha_fin = form.fecha_fin.data
            message = guardar_curso_programado(curso, fecha_ini, fecha_fin)
            if message:
                flash(message)
                return render_template("cursos/programar-curso.html", form=form)
            else:
                error = 'Problema al guardar, verifique los datos ingresados'
                return render_template("cursos/programar-curso.html", form=form, error=error)
        else:
            return render_template("cursos/programar-curso.html", form=form)
    else:
        lista_cursos = Curso.query.all()
        return render_template("cursos/programar-curso.html", lista_cursos=lista_cursos, form=form)

@cursos_bp.route('/cursos/alumnos-registrados', methods=['GET', 'DELETE'])
@login_required
def alumnos_registrados():
    if request.method == 'DELETE': 
        id = request.args.get('id') 
        a = AlumnoCurso.query.get(int(id))
        db.session.delete(a)
        db.session.commit()
        return {"message": "ok"}

app/templates/cursos/cursos-disponibles.html
{% extends "base_template.html" %}

{% block content %} 
<script>
  $( function() {
    $( ".my-atepicker" ).datepicker(
      $.datepicker.regional[ "es" ]
    );
    $( ".my-atepicker" ).datepicker( "option", "dateFormat", "dd/mm/yy");
  });
</script>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/cursos/partials/menu-cursos-tpl.html' %}
    </div>
    <div class="column is-9">
      <p class="subtitle"><strong>Cursos disponibles</strong></p>
      <table class="class table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <tr><th>#</th><th>Curso</th><th>Descripción</th></tr>
        {% for e in lista_cursos %}
          <tr>
            <td>{{ loop.index }}</td>
            <td>{{ e.nombre }}</td>
            <td>{{ e.descripcion }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock %}


 

app/templates/cursos/cursos-programados.html
{% extends "base_template.html" %}

{% block content %} 

<div class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/cursos/partials/menu-cursos-tpl.html' %}
    </div>
    <div class="column is-9">
    <p class="subtitle"><strong>Cursos programados</strong></p>
    <table class="class table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
      <tr>
        <th>#</th>
        <th>Curso</th>
        <th>F. Inicio</th>
        <th>F. Fin</th>
        <th  class="has-text-centered">Acciones</th>
      </tr>
      {% for e in lista_cursos %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ e.curso.nombre }}</td>
          <td>{{ e.fecha_inicio.strftime('%d-%m-%Y') }}</td>
          <td>{{ e.fecha_fin.strftime('%d-%m-%Y') }}</td>
          <td class="has-text-centered">
            <a href="{{ url_for('cursos.ver_curso_programado', id=e.id) }}">
              <span class="icon"><i class="fas fa-edit" title="Editar"></i> </span>
            </a>
            <span class="icon" style="cursor: pointer" onclick="eliminarCursoProgramado({{ e.id }})"><i class="fas fa-trash" title="Eliminar"></i> </span>
          </td>
        </tr>
      {% endfor %}
    </table>
    </div> 
  </div>
</div>

<script>
  function eliminarCursoProgramado(idx){
    var r = confirm("¿Estás seguro que deseas eliminar este registro?");
    if(r == true){
        $.ajax({
          url: '{{url_for("cursos.cursos_programados")}}',
          type: 'DELETE',
          data: JSON.stringify({ id: idx} ),
          success: function(result) {
            window.location.reload();
          }
      });
    } 
  }
</script>
{% endblock %}

app/templates/cursos/programar-curso.html
{% extends "base_template.html" %}

{% block content %} 
<script>
  $( function() {
    $( ".my-datepicker" ).datepicker(
      $.datepicker.regional[ "es" ]
    );
    $( ".my-datepicker" ).datepicker( "option", "dateFormat", "dd/mm/yy");
  });
</script>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/cursos/partials/menu-cursos-tpl.html' %}
    </div>
    <div class="column is-9">
      <p class="subtitle"><strong>Programar curso</strong></p>
      <form action="{{ url_for('cursos.programar_curso') }}" method="post" class="form" novalidate>
        {{ form.hidden_tag() }}
        <div class="field">
          <label class="label"> {{ form.curso.label }}</label>
          <div class="control">
            {{ form.curso(class_="input") }}
          </div>
          {% for error in form.curso.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="field">
          <label class="label"> {{ form.fecha_ini.label }}</label>
          <div class="control">
            {{ form.fecha_ini(class_="my-datepicker input") }}
          </div>
          {% for error in form.fecha_ini.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="field">
          <label class="label"> {{ form.fecha_fin.label }}</label>
          <div class="control">
            {{ form.fecha_fin(class_="my-datepicker input") }}
          </div>
          {% for error in form.fecha_fin.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
        </div>
        <div>
          <span class="has-text-danger">{{ error }}</span>
        </div>
        <div class="field">
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              <ul class=flashes>
              {% for message in messages %}
                <li><span class="has-text-link">{{ message }}</span></li>
              {% endfor %}
              </ul>
            {% endif %}
          {% endwith %}
        </div>
        <nav class="level">
          <!-- Right side -->
          <div class="level-right">
            <p class="level-item">
              {{ form.submit(class_="button is-link") }}
            </p>
          </div>
        </nav>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app/templates/cursos/subir-certificado.html
{% extends "base_template.html" %}

{% block content %}
<script>
  $(function () {
    $(".my-atepicker").datepicker(
      $.datepicker.regional["es"]
    );
    $(".my-atepicker").datepicker("option", "dateFormat", "dd/mm/yy");
  });
</script>

<div class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/cursos/partials/menu-cursos-tpl.html' %}
    </div>
    <div class="column is-9">
      <p class="subtitle"><strong>Subir certificado PDF</strong></p>
      <form action="{{ url_for('cursos.curso_alumno_subir_certificado', cid=cid, aid=aid) }}" 
      method="post" class="form"
        enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <div class="field">
          <label class="label">Subir archivo</label>
          <div class="control">
            <input type="file" name="document" class="input">
          </div>
          {% for error in form.document.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
        </div>
        <nav class="level">
          <!-- Right side -->
          <div class="level-right">
            <p class="level-item">
              {{ form.submit(class_="button is-link") }}
            </p>
          </div>
        </nav>
      </form>
      <br><br>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      <ul class=flashes>
        {% for message in messages %}
        <li><span class="has-text-link">{{ message }}</span></li>
        {% endfor %}
      </ul>
      {% endif %}
      {% endwith %}
    </div>
  </div>
</div>

{% endblock %}

app/templates/cursos/ver-curso-programado.html
{% extends "base_template.html" %}

{% block content %}
<div id="vm" class="container">
  <div class="columns">
    <div class="column is-3">
      {% include '/cursos/partials/menu-cursos-tpl.html' %}
    </div>
    <div class="column is-9">
      <p class="subtitle"><strong>Curso programado</strong></p><br />
      <form action="{{url_for('cursos.ver_curso_programado', id=form.id.data)}}" method="post" class="form" novalidate>
        {{ form.hidden_tag() }}
        <div class="field is-horizontal">
          <div class="field-body">
            <div class="field-label is-normal">
              <label class="label"> {{ form.curso.label }}</label>
            </div>
            <div class="field">
              <p class="control is-expanded has-icons-left">
                {{ form.curso(class_="input  has-background-grey-lighter") }}
              </p>
            </div>
            <div class="field-label is-normal">
              <label class="label"> {{ form.fecha_ini.label }}</label>
            </div>
            <div class="field">
              {{ form.fecha_ini(class_="my-datepicker input") }}
            </div>
            <div class="field">
              {{ form.submit(class_="button is-link") }}
            </div>
          </div>
        </div>
        <div>
          {% for error in form.curso.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
          {% for error in form.fecha_ini.errors %}
          <span class="has-text-danger">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="field">
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          <ul class=flashes>
            {% for message in messages %}
            <li><span class="has-text-link">{{ message }}</span></li>
            {% endfor %}
          </ul>
          {% endif %}
          {% endwith %}
        </div>
      </form>

      <hr>

      <nav class="level">
        <!-- Left side -->
        <div class="level-left">
          <div class="level-item">
            <p class="subtitle is-5">
              <strong>Alumnos inscritos</strong>
            </p>
          </div>
        </div>
        <!-- Right side -->
        <div class="level-right">
          <p class="level-item"><a class="button is-success" v-on:click="launch">Agregar</a></p>
        </div>
      </nav>

      <table class="class table is-bordered is-striped 
      is-narrow is-hoverable is-fullwidth">
        <tr>
          <th>#</th>
          <th>Dni</th>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Celular</th>
          <th class="has-text-centered">Certificado</th>
          <th class="has-text-centered">Acciones</th>
        </tr>
        {% for e in lista %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ e.alumno.dni }}</td>
          <td>{{ e.alumno.nombre }}</td>
          <td>{{ e.alumno.apellido }}</td>
          <td>{{ e.alumno.celular }}</td>
          <td class="has-text-centered">
              {% if e.certificado %}
              <a href="{{ url_for('cursos.download_file', filename=e.certificado) }}">
                <span>
                <i class="fas fa-file-pdf" title="Descargar"></i>
                  Descargar certificado
                </span>
               </a> 
              {% else %}
               <a href="{{ url_for('cursos.curso_alumno_subir_certificado', cid=form.id.data, aid=e.alumno.id) }}"> 
                <span>
                <i class="fas fa-upload" title="Subir certificado"></i>
                  Subir certificado
                </span>
               </a>
              {% endif %}
          </td>
          <td class="has-text-centered">
            <span class="icon" style="cursor: pointer" 
            v-on:click="retirarAlumno({{ e.id }})"><i
            class="fas fa-trash" title="Eliminar"></i> </span>
          </td>
        </tr>
        {% endfor %}
      </table>

      <div class="modal" v-bind:class="{'is-active':isActive}">
        <div class="modal-background"></div>
        <div class="modal-card" style="width: 840px">
          <header class="modal-card-head">
            <p class="modal-card-title">Agregar Alumnos</p>
          </header>
          <section class="modal-card-body" >
            <nav class="level">
              <!-- Left side -->
              <div class="level-left">
                <div class="level-item">
                  <label class="label">Buscar : </label>
                </div>
                <div class="level-item">
                  <div class="field has-addons">
                    <p class="control">
                      <input type="text" class="input"
                        v-model="slug"
                        placeholder="Buscar por slug, dni, nombre,apellido"/>
                    </p>
                    <p class="control">
                      <input type="button" class="button is-link" v-on:click="buscarAlumnoXFiltro"  value="Buscar" />
                    </p>
                  </div>
                </div>
              </div>
            </nav>

            <table class="class table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
              <tr>
                <th>
                  <input type="checkbox" v-model="isCheckAll" @change="checkAll($event)"></label>
                </th><th>Dni</th><th>Nombres</th><th>Apellidos</th>
                <th>Correo</th><th>Celular</th><th>Slug</th>
              </tr>
              <tr v-for="(item, index) in lista">
                <td><label class="checkbox">
                  <input type="checkbox" v-model="item.checked"></label>
                </td>
                <td>[[item.dni]]</td>
                <td>[[item.nombre]]</td>
                <td>[[item.apellido]]</td>
                <td>[[item.correo]]</td>
                <td>[[item.celular]]</td>
                <td>[[item.slug]]</td>
              </tr>
            </table>
          </section>
          <footer class="modal-card-foot">
            <button v-on:click="guardarAlumnosSeleccionados" 
            class="button is-success">Agregar</button>
          </footer>
        </div>
        <button class="modal-close is-large" aria-label="close" v-on:click="close"></button>
      </div>
    </div>
  </div>
</div>
<script>
  const vm = new Vue({ // Again, vm is our Vue instance's name for consistency.
    el: '#vm',
    delimiters: ['[[', ']]'],
    data: {
        isActive: false,
        lista: [],
        isCheckAll: false,
        slug: ""
    },
    methods: {
      checkAll: function(e) {
        this.$nextTick(() => {
          for(i=0;i<this.lista.length; i++){
            var item = this.lista[i];
            if(this.isCheckAll){
              item.checked = true;
            }else{
              item.checked = false;
            }
          }
        })
      },
      buscarAlumnoXFiltro: function() {
        var params = { op: 'filtro-mixto', slug: this.slug};
        try {
          axios.get('{{url_for("alumnos.lista_completa")}}', {params: params})
          .then(
            response => {
              this.lista = [];
              var data = response.data;
              for(i=0;i<data.length; i++){
                var item = data[i];
                item.checked = false;
                this.lista.push(item);
              }
            }
          )
          .catch(error => {
            console.log(error)
          })
          //.finally(() => this.loading = false)
        } catch (error) {
          console.log(error);
        }
      }, 
      subirCertificado: function(id){
        var c = confirm("¿Está seguro que desea eliminar este registro?");
        if(c){
          var params = { id: id};
          axios.delete('{{url_for("cursos.alumnos_registrados")}}', {params: params})
          .then(
            response => {
              if(response.data.message == "ok"){
                window.location.reload()
              }
            }
          )
          .catch(error => {
            console.log(error)
          })
        }else{
          console.log("no");
        }
      },
      retirarAlumno: function(id){
        var c = confirm("¿Está seguro que desea eliminar este registro?");
        if(c){
          var params = { id: id};
          axios.delete('{{url_for("cursos.alumnos_registrados")}}', {params: params})
          .then(
            response => {
              if(response.data.message == "ok"){
                window.location.reload()
              }
            }
          )
          .catch(error => {
            console.log(error)
          })
        }else{
          console.log("no");
        }
      },
      guardarAlumnosSeleccionados: function(){
        let ids = []
        for(i=0;i<this.lista.length; i++){
          var item = this.lista[i];
          if(item.checked){
            ids.push(item.id);
          }
        }
        // Inscribir alumnos en el curso.
        var cid = '{{form.id.data}}';
        var params = { op: 'inscribir-alumnos',cid: cid ,ids: ids};
        axios.put('{{url_for("cursos.cursos_programados")}}', {params: params})
          .then(
            response => {
              if(response.data.message == "ok"){
                this.isActive = false;
                window.location.reload()
              }
            }
          )
          .catch(error => {
            console.log(error)
          })
      },
      launch: function() {
        this.isActive = true;
      },
      close: function() {
        this.isActive = false;
      }
    }
})
</script>
{% endblock %}